### ISSUE TITLE
Questions about Dynamic Graph

### ISSUE THREAD

**Issue by zhenshan0127** [xinliu20/GraphCSPN_ECCV2022#2]
Hello Liu,

Thanks for great work! When I read the paper, I had two questions about learning process of dynamic graph:

1. In each iteration, the affinity patches (affinity matrix) are different. So, it is different from the original SPN idea. Is it possible that the whole spatial propagation process is not stabilized? Or, does it guarantee that the result tends to a stable correct result as the iteration progress?  (I know it converges from the excellent experiment results.) Then, what's the  $\phi$ MLP learning?

2. I think the attention mechanism is used to control the weight of neighors' contribution. And graph is dynamic because of new estimation of depth map, and it means some nodes are disconnected from the center node and some new nodes are connected to it. Can I say that when training, the weights of the nodes that are disconnected drop directly to 0 and at the same time, some new nodes invloves in the attention mechansim? Therefore, once the spatial propagation tends to be stabilized correctly, K-nearest algorithm accelerates the propagation process.

Thank you for your time!

**Comment by xinliu20** [comment]
Thanks for the very insightful questions! 1) The whole spatial propagation process is stable since a more accurate result ( $\phi$ learns to refine it) is obtained after each iteration. SPNs originate in anisotropic diffusion, which guarantees the convergence of the iteration process. In this view,  the original SPN models the linear diffusion process, while GraphCSPN models the nonlinear diffusion process. Please see the supplement for more discussions. 2) Yes. The graph is dynamically constructed for each iteration, so the connected nodes are different by setting different weights (zero for disconnected ones).

**Comment by zhenshan0127** [comment]
Hello @xinliu20 

Thank you for reply! It's useful for me to understand your work better. 

If I have other questions, I will submit a new issue.
